// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

//#include <ctre/phoenix/motorcontrol/can/TalonSRX.h>
#include <frc2/command/SubsystemBase.h>
#include <rev/CANSparkMax.h>
#include <frc/motorcontrol/MotorControllerGroup.h>

#include "Constants.h"

class Climber: public frc2::SubsystemBase {

private:
    rev::CANSparkMax m_climberMotor1{ClimberConstants::kClimberMotor1Port, rev::CANSparkMax::MotorType::kBrushless};
    rev::CANSparkMax m_climberMotor2{ClimberConstants::kClimberMotor2Port, rev::CANSparkMax::MotorType::kBrushless};
    //frc::MotorControllerGroup m_climberMotors{m_climberMotor1, m_climberMotor2};
    
public:
    Climber();

    void Periodic() override;
    void SimulationPeriodic() override;
    void ClimberRaise();
    void ClimberLower();
    void ClimberStop();
    void ClimberScanEncoders();

    rev::SparkRelativeEncoder m_climberEncoder1 = m_climberMotor1.GetEncoder();
    rev::SparkRelativeEncoder m_climberEncoder2 = m_climberMotor2.GetEncoder();

    double ClimberEncoder2Value;

};