// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "commands/IntakeExpelCommand.h"

IntakeExpelCommand::IntakeExpelCommand(Intake* m_intake)
:m_intake(m_intake){

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("IntakeExpelCommand");
    AddRequirements(m_intake);
}

// Called just before this Command runs the first time
void IntakeExpelCommand::Initialize() {
   m_intake->IntakeExpel();
}

// Called repeatedly when this Command is scheduled to run
void IntakeExpelCommand::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeExpelCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void IntakeExpelCommand::End(bool interrupted) {
    m_intake->IntakeStop();
}

bool IntakeExpelCommand::RunsWhenDisabled() const {
    return false;
}