// THIS FILE IS FROM 2024 - OUR 2025 CODE WILL PROBABLY NOT KEEP THIS FILE, IT IS JUST TO MAKE PROGRAMMING 2025 EASIER

// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "subsystems/Climber.h"

#include <frc/smartdashboard/SmartDashboard.h>
#include <wpi/raw_ostream.h> // for wpi outs()


Climber::Climber(){
    SetName("Climber");
    SetSubsystem("Climber");

    //AddChild("ClimberMotor1", &m_climberMotor1);
    m_climberMotor1.SetInverted(false);

    //AddChild("ClimberMotor2", &m_climberMotor2);
    m_climberMotor2.SetInverted(true);

    //AddChild("ClimberMotors", &m_climberMotors);

    m_climberMotor1.SetIdleMode(rev::CANSparkBase::IdleMode::kBrake);
    m_climberMotor2.SetIdleMode(rev::CANSparkBase::IdleMode::kBrake);
}

void Climber::Periodic() {
    // Put code here to be run every loop
    ClimberScanEncoders();//TODO needed???????? - what im saying is change it so it checks within the function instead of needing 2 functions
}

void Climber::SimulationPeriodic() {
}

// Put methods for controlling this subsystem here and call from commands

void Climber::ClimberRaise(){ 
    // Run Climber
    if(ClimberEncoder2Value > -492)
    {
        m_climberMotor1.Set(-1.0);
        m_climberMotor2.Set(-1.0);
    }
    else
    {
        m_climberMotor1.Set(0.0);
        m_climberMotor2.Set(0.0);
    }
        //m_climberMotor1.Set(-0.5);
        //m_climberMotor2.Set(-0.5); 
} 

void Climber::ClimberLower(){
    // Run Expel

    if(ClimberEncoder2Value < 0)
    {
        m_climberMotor1.Set(1.0);
        m_climberMotor2.Set(1.0);
    }
    else
    {
        m_climberMotor1.Set(0.0);
        m_climberMotor2.Set(0.0);
    }
        //m_climberMotor1.Set(0.5);
        //m_climberMotor2.Set(0.5);
}

void Climber::ClimberStop(){
    // stop the Climber motor
    m_climberMotor1.Set(0.0);
    m_climberMotor2.Set(0.0);  
}

void Climber::ClimberScanEncoders(){//TODO needed???????? - what im saying is change it so it checks within the function instead of needing 2 functions
    // get climberencoder values for limit switch thingy
    ClimberEncoder2Value = m_climberEncoder2.GetPosition();
    frc::SmartDashboard::PutNumber("climberencoder2value", ClimberEncoder2Value);
}